arch: s390x
services:
  - docker
env:
  global:
    - TEST_DIR="$PWD/"
    - TEST_SCRIPT="test.sh"
    - BUILD_DIR="$PWD/10.0/jdk11/adoptopenjdk-hotspot/"
    - REPO="quay.io/ibmz/tomcat"
    - TAG="$REPO:10.0.0"
before_script: 
  - cd $TEST_DIR && chmod +x $TEST_SCRIPT
  - docker login quay.io -u $ROBOT -p $ROBOT_TOKEN
script: 
  - docker build $BUILD_DIR --tag $TAG
  - cd $TEST_DIR && bash $TEST_SCRIPT 
after_script:
  - docker push $REPO
